Remove "stable" scrollbar-gutter
KTH/style pull request #62
Opened 2024-06-25 11:39 UTC by exacs

2024-07-01 12:35 UTC, ahrsjo commented
AB#3889

2024-07-02 07:01 UTC, ahrsjo commented
AB#3889

2024-08-14 10:58 UTC, ahrsjo approved these changes
![giphy](https://github.com/user-attachments/assets/aa5b2385-76fc-4d10-803d-e34497dde2cc)

2024-08-26 11:16 UTC, EllenWiderstrand requested changes
As discussed on Slack: The "Logga in" button is jumping (it is first displayed to the left and then to the right where it is supposed to be)

https://github.com/user-attachments/assets/6e79f947-d860-4846-a00c-30eb17c3d580

2024-08-26 13:37 UTC, EllenWiderstrand approved these changes

2024-08-26 13:37 UTC, EllenWiderstrand commented on @kth/style/scss/components/kpm.scss
> +// This file contains the minimal CSS needed to avoid layout shifts and other
Nice!

2024-08-26 13:39 UTC, merged